spring.application.name=notification-service
spring.config.import=${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

# MySQL configuration
spring.datasource.url=${MYSQL_URL_JDBC:jdbc:mysql://localhost:3306/}hms-notification-service?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_ACCOUNT:root}
spring.datasource.password=${MYSQL_ACCOUNT:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Twilio configuration
twilio.account_sid=${TWILIO_ACCOUNT_SID}
twilio.auth_token=${TWILIO_AUTH_TOKEN}
twilio.phone_number=${TWILIO_PHONE_NUMBER}

# Email configuration
spring.mail.host=smtp.sendgrid.net
spring.mail.port=2525
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp

# for zipkin
logging.pattern.level="%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
management.tracing.propagation.type=b3

spring.cloud.openfeign.okhttp.enabled=true